---
title: "Assignment 4, EDDA 2017"
author: "Martin de la Riva(11403799) and Kieran O'Driscoll(11426438), Group 23"
date: "08 May 2017"
output:
  pdf_document: default 
  html_document: default
highlight: tango
fontsize: 11pt
---
```{r}
library(multcomp)
library(lme4)
```

# Assignment 4

## Exercise 1

### 1.
For this exercise  
```{r}
bread_data=read.table("data\\bread.txt", header=TRUE)
I=nrow(unique(bread_data['environment']))
J=nrow(unique(bread_data['hours']));
N=3 #number of tests per experiment
randomization = rbind(rep(1:I,each=N*J),rep(1:J,N*I),sample(1:(N*I*J))) #randomization code
```

### 2.


```{r}
par(mfrow=c(2,2))
boxplot(hours~environment,data=bread_data, main="Plot of hours and environment", 
  	xlab="Environment", ylab="Hours")
boxplot(hours~humidity,data=bread_data, main="Plot of hours and humidity", 
  	xlab="Humidity", ylab="Hours")
attach(bread_data)

interaction.plot(environment, humidity, hours)
interaction.plot(humidity, environment, hours)
```


### 3

```{r}
#Analysisof variance
#2 way alnova
bread_data$environment=as.factor(bread_data$environment)
bread_data$humidity=as.factor(bread_data$humidity)
pvcaov=lm(hours~environment*humidity,data=bread_data)
print(anova(pvcaov))
```


### 4.

```{r}
contrasts(bread_data$environment)=contr.sum
contrasts(bread_data$humidity)=contr.sum
pvcaov2=lm(hours~environment*humidity, data=bread_data)
print(summary(pvcaov2))
```


```{r}
  print(confint(pvcaov2))
```


###5.

```{r}
  qqnorm(residuals(pvcaov2))
```
Not normal so probably contains outliers
```{r}
print(residuals(pvcaov2)) # look for residuals that are outside std
```

```{r}
  cooks.distance(pvcaov2)
  #plot point on graph with cooks distance and levenes distance
  #library(car)  influencePlot(pvcaov2)
```




## Exercise 2


### 1.

```{r}
I=3; B=5; N=15 # 15 students
for (i in 1:B) print(sample(1:(N*I)))

```

### 2.

```{r}
search_data=read.table("data\\search.txt", header=TRUE)
par(mfrow=c(2,2))
boxplot(time~skill,data=search_data, main="Plot of time and skill", 
  	xlab="Skill", ylab="Time")
boxplot(time~interface,data=search_data, main="Plot of time and interface", 
  	xlab="Interface", ylab="Time")
attach(search_data)
interaction.plot(skill, interface, time)
interaction.plot(interface, skill, time)

```
Big correlations!!

### 3.

```{r}
search_data=read.table("data\\search.txt", header=TRUE)#need for reset 
f = (function (x) gsub(" ", "", paste("skill.", x), fixed = TRUE))
search_data['skill'] = apply(search_data['skill'], 1, f)
f = (function (x) gsub(" ", "", paste("interface.", x), fixed = TRUE))
search_data['interface'] = apply(search_data['interface'], 1, f)

temp_data = search_data
temp_data['interface'] = paste("interface", temp_data['interface']) #change to category
new_data = xtabs(time~interface+skill,data=search_data)

aovpen=lm(time~interface+skill,data=search_data)
print(anova(aovpen))
print(summary(aovpen))

```

### 4.
4. Estimate the time it takes a typical user of skill level 4 to find the product
on the website if the website uses interface 3.

```{r}
par(mfrow=c(2,1))
attach(search_data)
interaction.plot(skill,interface,time)
interaction.plot(interface,skill,time) 

```

###5.

```{r}
par(mfrow=c(1,2))
qqnorm(residuals(aovpen))
plot(fitted(aovpen),residuals(aovpen))

```

###6.

```{r}
friedman.test(time,interface,skill)
```

###7.

```{r}
aovpen=lm(time~interface,data=search_data)
print(anova(aovpen))
print(summary(aovpen))
```

###Excercise 3

```{r}
cream_data=read.table("data\\cream.txt", header=TRUE)
#starter+batch+position
cream_data['position'] = factor(cream_data$position)
cream_data['batch'] = factor(cream_data$batch)
cream_data['starter'] = factor(cream_data$starter)
model = lm(acidity???starter+batch+position, data=cream_data)
print(model)
```


###2.
```{r}
pvcaov=lm(acidity???starter+batch+position, data=cream_data)
summary(pvcaov)

##error
pvcmult=glht(pvcaov,linfct=mcp(resin == 1))
summary(pvcmult)

#pvcmult=glht(model,linfct=mcp(starter))
'pvcmult
```


###3.

```{r}
summary(model)

```

##4.

